version: '3'

volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: docker.env
    ports:
      - "6380:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: always
    env_file: docker.env
    ports:
      - "5480:6379"
    volumes:
      - redis_data:/data

networks:
  postgres:
    driver: bridge

